name: notion-desktop-reborn
version: '2.0.0'
summary: Desktop application for Notion with tab support and Linux optimization
description: |
  Notion Desktop Reborn is a feature-rich desktop application for Notion that provides
  visual tab management, native Linux keyboard shortcuts, and enhanced window management.
  
  Features:
  - Visual tab bar with full tab management
  - Native Linux keyboard shortcuts (uses Ctrl instead of Super/Meta)
  - Perfect fullscreen experience with no layout issues
  - Auto dark/light theme support that follows system preferences
  - Enhanced window management for all screen modes
  - Force resize functionality (Ctrl+Shift+R) for layout correction
  - Intelligent platform detection optimized for Linux
  - Professional-grade user experience
  
  Perfect for Linux users who want a native desktop experience for Notion
  with proper keyboard shortcuts and seamless window management.

grade: stable
confinement: strict
base: core22
architectures:
  - build-on: amd64

icon: build/icons/icon.png

apps:
  notion-desktop-reborn:
    command: bin/notion-desktop.sh
    plugs:
      - browser-support
      - network
      - network-bind
      - audio-playback
      - audio-record
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
      - home
      - removable-media
    environment:
      DISABLE_WAYLAND: 1
      TMPDIR: $XDG_RUNTIME_DIR

parts:
  notion-desktop:
    plugin: dump
    source: dist/linux-unpacked/
    organize:
      '*': lib/
    stage:
      - lib/*
    
  wrapper:
    plugin: dump
    source: .
    organize:
      notion-desktop.sh: bin/notion-desktop.sh
    stage:
      - bin/notion-desktop.sh
    prime:
      - bin/notion-desktop.sh
